## 1

In [1]:
import numpy as np

In [12]:
def reverse_np_array (N):
    return np.arange(0,N)[::-1]

In [13]:
reverse_np_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2

In [44]:
def sum_diag (N):
    a = np.diag(reverse_np_array(N))
    print(a)
    print (f'Сумма значений по диагонали {np.trace(a)}')

In [48]:
sum_diag(7)

[[6 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]]
Сумма значений по диагонали 21


## 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [58]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

In [59]:
from numpy import linalg

In [60]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [61]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## 4

In [63]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [64]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [89]:
def cosine (users_stats, next_user_stats):
    """   
    Функция считает косинус угла между вектором нового пользователя и векторами существующих пользователей из базы.
    Возвращает максимальный угол из найденных, т.е. наиболее похожего пользователя и его индекс в базе.
    """
    cosines = []
    for i in users_stats:
        aLength = np.linalg.norm(i)
        bLength = np.linalg.norm( next_user_stats )
        cosines.append(np.dot(i, next_user_stats)/(aLength * bLength))
    return max(cosines), cosines.index(max(cosines))

In [90]:
cosine (users_stats, next_user_stats)

(0.9486832980505138, 7)